version: '2.4'
services:

    # ---------------------------------
    # TRAEFIK
    # ---------------------------------
    traefik:
        image: traefik:2.4
        volumes:
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
        links:
          - server
        ports:
         - "80:80"
         - "127.0.0.1:8080:8080"

    # ---------------------------------
    # DB
    # ---------------------------------
    mariadb:
      container_name: mariadb
      image: mariadb:10.5.9
      hostname: mariadb
      command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME:-database}
        MYSQL_USER: ${DB_USER:-user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-user}
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD:-user}
      volumes:
        - vol-db-data:/var/lib/mysql
      ports:
        - '127.0.0.1:3306:3306'
      labels:
        - traefik.enable=false
      

    # ---------------------------------
    # SERVER
    # ---------------------------------
    server:
      hostname: server
      build: .
      restart: always
      links:
        - mariadb
      labels:
        - "traefik.http.routers.${NAME:-app}.rule=PathPrefix(`/`)"
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.name=server_id
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.httpOnly=true
      volumes:
        - vol-server-data:/usr/src/app/static
        - ./app:/app

    # ---------------------------------
    # DRUPAL
    # ---------------------------------
    # server:
    #   hostname: server
    #   image: drupal
    #   restart: always
    #   volumes:
    #     - /drupal/modules:/opt/drupal/web/modules
    #     - /drupal/profiles:/opt/drupal/web/profiles
    #     - /drupal/themes:/opt/drupal/web/themes
    #   links:
    #     - mariadb
    #   labels:
    #     - "traefik.http.routers.${NAME:-app}.rule=PathPrefix(`/`)"
    #     - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.name=server_id
    #     - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.httpOnly=true


    # ---------------------------------
    # WORDPRESS
    # ---------------------------------
    # server:
    #   hostname: server
    #   image: wordpress:${WORDPRESS_VERSION:-latest}
    #   restart: on-failure
    #   environment:
    #     WORDPRESS_DB_HOST: mariadb:3306
    #     WORDPRESS_DB_NAME: ${DB_NAME:-database}
    #     WORDPRESS_DB_USER: ${DB_USER:-user}
    #     WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-user}
    #     WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX:-wp_}
    #     WORDPRESS_CONFIG_EXTRA: |
    #       define('FS_METHOD','direct');
    #       define('WP_DEBUG_LOG', true);
    #       define('WP_AUTO_UPDATE_CORE', false);
    #       define('WP_POST_REVISIONS', false);
    #       define('DISALLOW_FILE_EDIT', true);
    #       define('DISALLOW_FILE_MODS', true);
    #       define('WPMU_PLUGIN_DIR', ABSPATH . 'mu-plugins');
    #       define('WPMU_PLUGIN_URL', '/mu-plugins');
    #       define('WP_PLUGIN_DIR', ABSPATH . 'plugins');
    #   working_dir: /var/www/html
    #   volumes:
    #     - ./wordpress/mu-plugins:/var/www/html/mu-plugins
    #     - ./wordpress/themes:/var/www/html/wp-content/themes
    #     - ./wordpress/plugins:/var/www/html/plugins
    #     - ./conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    #   labels:
    #     - "traefik.http.routers.${NAME:-app}.rule=PathPrefix(`/`)"
    #     - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.name=server_id
    #     - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.httpOnly=true

    # ---------------------------------
    # Tools dev or integration
    # ---------------------------------
    mysql-admin:
      container_name: mysql-admin
      hostname: mysql-admin
      image: phpmyadmin/phpmyadmin:5.1.0
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-user}
        PMA_USER: ${DB_USER:-user}
        PMA_PASSWORD: ${DB_PASSWORD:-user}
      ports:
        - '127.0.0.1:3380:80'
      restart: always

volumes:
  vol-db-data:
    driver: local
  vol-server-data:
    driver: local